version: "3.8"

services: 
    
    nodered:
        container_name: "NodeRed"
        build: .
        restart: on-failure:3
        ports:
            - "1880:1880"
        env_file:
            - ${TB_ENVFILE}
        volumes:
            - ${TB_CONFIG_PATH}:/config

    portainer:
        container_name: "Portainer"
        image: "portainer/portainer-ce"
        restart: on-failure
        ports: 
            - "9000:9000"
        volumes: 
            - vol-portainer-data:/data
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    vol-portainer-data:
        name: portainer-data
    