version: "3.8"

services: 
    
    nodered:
        container_name: "NodeRed"
        build: .
        restart: on-failure
        ports:
            - "1880:1880"
        env_file:
            - envs.env
            # - envs_test.env
        volumes:
            - ./Config:/Config
            # - ./Data/flows.json:/data/flows.json
            # - ./Data/flows_cred.json:/data/flows_cred.json
            # - ./Data/settings.js:/data/settings.js

    portainer:
        container_name: "Portainer"
        image: "portainer/portainer-ce"
        restart: on-failure
        ports: 
            - "9000:9000"
        volumes: 
            - vol-portainer-data:/data
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    vol-portainer-data:
        name: portainer-data
    